# Generated by Django 2.2.7 on 2019-11-25 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100, verbose_name='用户id')),
                ('content', models.TextField(verbose_name='内容')),
                ('nickname', models.CharField(blank=True, max_length=20, null=True, verbose_name='用户昵称')),
                ('contact', models.CharField(blank=True, max_length=50, null=True, verbose_name='用户联系方式')),
                ('status', models.CharField(choices=[('active', '激活'), ('close', '关闭，下线')], default='active', max_length=20, verbose_name='状态')),
                ('reply', models.TextField(blank=True, null=True, verbose_name='回复')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('mtime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='scrapy代号')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='作者')),
                ('cname', models.CharField(max_length=100, verbose_name='名称')),
                ('link', models.CharField(max_length=200, verbose_name='主页')),
                ('favicon', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='favicon')),
                ('brief', models.CharField(max_length=200, verbose_name='简介')),
                ('star', models.IntegerField(default=20, verbose_name='评级')),
                ('freq', models.CharField(choices=[('小时', '每小时更新'), ('日更', '每天更新'), ('周更', '每周更新'), ('月更', '每月更新')], max_length=20, verbose_name='更新频率')),
                ('status', models.CharField(choices=[('active', '激活'), ('close', '关闭，下线')], db_index=True, default='active', max_length=20, verbose_name='状态')),
                ('copyright', models.IntegerField(blank=True, choices=[(0, '未知'), (10, '不可转载'), (20, '仅可转载摘要'), (30, '可以全文转载')], default=0, null=True, verbose_name='版权')),
                ('tag', models.CharField(blank=True, choices=[('前端', '前端'), ('客户端', '客户端'), ('后端', '后端'), ('全栈', '全栈'), ('产品', '产品'), ('营销', '营销'), ('安全', '安全'), ('设计', '设计'), ('测试', '测试'), ('运维', '运维'), ('刊物', '刊物'), ('算法', '算法'), ('大数据', '大数据'), ('RSS', 'RSS')], max_length=20, null=True, verbose_name='一个词形容')),
                ('rss', models.CharField(blank=True, max_length=200, null=True, verbose_name='RSS地址')),
                ('creator', models.CharField(blank=True, choices=[('system', '系统录入'), ('user', '用户提交')], default='system', max_length=20, null=True, verbose_name='创建人')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('mtime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='标题')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='作者')),
                ('uindex', models.IntegerField(db_index=True, unique=True, verbose_name='唯一地址')),
                ('content', models.TextField(verbose_name='内容')),
                ('src_url', models.CharField(max_length=500, verbose_name='原始链接')),
                ('status', models.CharField(choices=[('active', '激活'), ('close', '关闭，下线')], db_index=True, default='active', max_length=20, verbose_name='状态')),
                ('ctime', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('mtime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Site')),
            ],
        ),
    ]
